URL:   https://develop.mktgflow.seedooh.com/scheduling
BROWSER:    chrome

SUPER_ADMIN: {
          USERNAME: superadmin@seedooh.com,
          PASSWORD: seedooh13
  }

partnerName:  TrueMove
category:  Crypto
contactName:  Lee Jung ki
contactRole:  CEO
email:  laoprasert.k@gmail.com
agency:  DA Entertainment
address:  99/443 The Cabana Condo
billingEntity:  True Corporation

#database: {
#            test: eeee
#            test1: 222
#}