URL:   https://develop.mktgflow.seedooh.com
BROWSER:    chrome

SUPER_ADMIN: {
          USERNAME: superadmin@seedooh.com,
          PASSWORD: seedooh13
  }

USER: {
          USERNAME: kritsada@seedooh.com,
          PASSWORD: Password@2
}
